### PR TITLE
Attempt at getting an async audio player working

### LINKED ISSUE #25: Play() should be declared as async as it is its default behavior.
When Play() is invoked it runs asynchronously. 
I like it but it might be nice to declare it as an asynchronous function so it can be awaited.

https://user-images.githubusercontent.com/2603287/188267318-574c7492-06ab-46c0-9c71-ee3702cbf2c2.mp4

### PR DESCRIPTION
**Pull request by bijington**
Fixes #25

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
Looks good to me! Simple but effective :D

**Comment by bijington** [comment]
I can't decide if this is the best API surface for the async part. Currently we could use the player as follows:

```csharp
CancellationTokenSource cancellationTokenSource;

public async Task Play()
{
    await asyncAudioPlayer.PlayAsync(cancellationTokenSource.Token);
}

public void Stop()
{
    cancellationTokenSource.Cancel();
}
```

Is this fine or should we consider providing a Stop method that would call `cancellationTokenSource.Cancel();` in the `AsyncAudioPlayer`?

**Comment by jfversluis** [comment]
Hm yeah I do think I prefer to (also) have a stop method in the player.

One doesn't rule out the other, right? You can still use the CancellationToken manually if that's what you want, or you call Stop and we will do it for you.

**Comment by bijington** [comment]
@jfversluis I think this is ready for a review now. One thing I wasn't completely sure on was the lack of properties on `AsyncAudioPlayer` like `Volume`, etc. but users can pass in an `IAudioPlayer` into the ctor to allow them to customise bits if they wanted.

**Comment by jfversluis** [comment]
>  One thing I wasn't completely sure on was the lack of properties on AsyncAudioPlayer like Volume, etc. but users can pass in an IAudioPlayer into the ctor to allow them to customise bits if they wanted.

Yeah let's see if people can figure it out or not, or maybe add a little bit of documentation around that?

**Comment by jfversluis** [comment]
Thanks for making this happen ✨

**Pull request merged**
